locals {
  empty_queue = {
    description           = null
    hours_of_operation_id = null
    status                = null
    quick_connect_ids     = []
    tags                  = {}
  }

  # Build as a map to keep conditional typing consistent when returning {} on secondary regions.
  primary_queues = {
    ch_dnis_error = {
      description           = "Error Queue for DNIS."
      hours_of_operation_id = try(module.amazon_connect.hours_of_operations["dnis_error_hours"].hours_of_operation_id, data.aws_connect_hours_of_operation.dnis_error_hours.hours_of_operation_id)
      status                = "ENABLED"
      quick_connect_ids     = []
      tags                  = local.tags
    }
    ch_quick_connect_queue = {
      description           = "Quick Connect Queue"
      hours_of_operation_id = try(module.amazon_connect.hours_of_operations["ch_24x7_hours"].hours_of_operation_id, data.aws_connect_hours_of_operation.ch_24x7_hours.hours_of_operation_id)
      status                = "ENABLED"
      quick_connect_ids = [
        data.aws_connect_quick_connect.jilliann_perez.quick_connect_id,
        data.aws_connect_quick_connect.janine_gutierrez.quick_connect_id,
        data.aws_connect_quick_connect.vanessa_osorio.quick_connect_id,
        data.aws_connect_quick_connect.christina_feindt.quick_connect_id,
        data.aws_connect_quick_connect.melissa_jevic.quick_connect_id,
        data.aws_connect_quick_connect.cathy_wallin.quick_connect_id,
        data.aws_connect_quick_connect.avital_rosenberg.quick_connect_id,
        data.aws_connect_quick_connect.adria_french.quick_connect_id,
        data.aws_connect_quick_connect.denise_lopez.quick_connect_id,
        data.aws_connect_quick_connect.eileen_ball.quick_connect_id,
        data.aws_connect_quick_connect.inessa_tsygan.quick_connect_id,
        data.aws_connect_quick_connect.jacqueline_alvarez.quick_connect_id,
        data.aws_connect_quick_connect.janet_jones.quick_connect_id,
        data.aws_connect_quick_connect.jean_kaplan.quick_connect_id,
        data.aws_connect_quick_connect.jennifer_quittley.quick_connect_id,
        data.aws_connect_quick_connect.jennifer_sullivan.quick_connect_id,
        data.aws_connect_quick_connect.madeline_dipietro.quick_connect_id,
        data.aws_connect_quick_connect.maria_lent.quick_connect_id,
        data.aws_connect_quick_connect.maria_vallejos.quick_connect_id,
        data.aws_connect_quick_connect.marie_cadestin.quick_connect_id,
        data.aws_connect_quick_connect.mary_zebrowski_vuolo.quick_connect_id,
        data.aws_connect_quick_connect.mily_febus.quick_connect_id,
        data.aws_connect_quick_connect.molly_desarme.quick_connect_id,
        data.aws_connect_quick_connect.nancy_nunez.quick_connect_id,
        data.aws_connect_quick_connect.tara_elzey.quick_connect_id,
        data.aws_connect_quick_connect.tia_thomas.quick_connect_id,
        data.aws_connect_quick_connect.wendy_valencia.quick_connect_id,
        data.aws_connect_quick_connect.beatrice_gomez.quick_connect_id,
        data.aws_connect_quick_connect.sulay_inoa_guzman.quick_connect_id,
        data.aws_connect_quick_connect.jesenia_hernandez.quick_connect_id,
        data.aws_connect_quick_connect.miriam_rodriguez.quick_connect_id,
        data.aws_connect_quick_connect.ruby_gonzalez.quick_connect_id,
        data.aws_connect_quick_connect.sarah_thomas.quick_connect_id,
        data.aws_connect_quick_connect.stephanie_vallejo.quick_connect_id,
        data.aws_connect_quick_connect.robert_santos_perez.quick_connect_id,
        data.aws_connect_quick_connect.catherine_garcia.quick_connect_id,
        data.aws_connect_quick_connect.nnenna_nwanonyiri.quick_connect_id,
        data.aws_connect_quick_connect.jessica_mendoza.quick_connect_id,
        data.aws_connect_quick_connect.indiana_luciano.quick_connect_id,
        data.aws_connect_quick_connect.damaris_lopez_cruz.quick_connect_id,
        data.aws_connect_quick_connect.fiorela_valdez.quick_connect_id,
        data.aws_connect_quick_connect.awilda_rios.quick_connect_id,
        data.aws_connect_quick_connect.maria_penaherrera.quick_connect_id,
        data.aws_connect_quick_connect.ana_joza_mera.quick_connect_id,
        data.aws_connect_quick_connect.carmen_rodriguez.quick_connect_id,
        data.aws_connect_quick_connect.linette_roman.quick_connect_id,
        data.aws_connect_quick_connect.andrea_morris.quick_connect_id,
        data.aws_connect_quick_connect.mercy_norales.quick_connect_id,
        data.aws_connect_quick_connect.michael_real.quick_connect_id,
        data.aws_connect_quick_connect.jacqueline_garcia.quick_connect_id,
        data.aws_connect_quick_connect.claudia_gelin.quick_connect_id,
        data.aws_connect_quick_connect.genesis_rodriguez.quick_connect_id,
        data.aws_connect_quick_connect.leandra_aguirrediaz.quick_connect_id,
        data.aws_connect_quick_connect.alejandra_marin_giraldo.quick_connect_id,
        data.aws_connect_quick_connect.estefania_sanchez.quick_connect_id,
        data.aws_connect_quick_connect.daniela_sanchez_marin.quick_connect_id,
        data.aws_connect_quick_connect.wallys_howe.quick_connect_id,
        data.aws_connect_quick_connect.nancy_rodriguez_navarro.quick_connect_id,
        data.aws_connect_quick_connect.roshio_quintana.quick_connect_id,
        data.aws_connect_quick_connect.elaine_iudici.quick_connect_id,
        data.aws_connect_quick_connect.yesenia_delrio.quick_connect_id,
        data.aws_connect_quick_connect.johan_witton_moyano.quick_connect_id,
        data.aws_connect_quick_connect.mauricio_luna.quick_connect_id,
        data.aws_connect_quick_connect.ariel_reinoso.quick_connect_id,
        data.aws_connect_quick_connect.soraya_bedon.quick_connect_id,
        data.aws_connect_quick_connect.giselle_ventura.quick_connect_id,
        data.aws_connect_quick_connect.giselle_tejada.quick_connect_id,
        data.aws_connect_quick_connect.iliana_correa.quick_connect_id,
        data.aws_connect_quick_connect.esthefany_gomez.quick_connect_id,
        data.aws_connect_quick_connect.alicia_swaby.quick_connect_id,
        data.aws_connect_quick_connect.rosangela_papageorgiou.quick_connect_id,
        data.aws_connect_quick_connect.gabriela_herrera.quick_connect_id,
        data.aws_connect_quick_connect.alexandra_vargas.quick_connect_id,
        data.aws_connect_quick_connect.lorena_hantsoulis.quick_connect_id,
        data.aws_connect_quick_connect.leislanimillie_sotomayor.quick_connect_id,
        data.aws_connect_quick_connect.jessica_reyes.quick_connect_id,
        data.aws_connect_quick_connect.barbara_garcia.quick_connect_id,
        data.aws_connect_quick_connect.elizabeth_sexton.quick_connect_id,
        data.aws_connect_quick_connect.elizabeth_coronado.quick_connect_id,
        data.aws_connect_quick_connect.yoly_medrano.quick_connect_id,
        data.aws_connect_quick_connect.reynaldo_rivera.quick_connect_id,
        data.aws_connect_quick_connect.shyra_maldonado.quick_connect_id,
        data.aws_connect_quick_connect.erica_alejandro.quick_connect_id,
        data.aws_connect_quick_connect.carisa_bautista.quick_connect_id,
        data.aws_connect_quick_connect.jahaira_allende.quick_connect_id,
        data.aws_connect_quick_connect.susan_hall.quick_connect_id,
        data.aws_connect_quick_connect.nora_torres.quick_connect_id,
        data.aws_connect_quick_connect.samantha_cordero.quick_connect_id,
        data.aws_connect_quick_connect.patrikia_baynes.quick_connect_id,
        data.aws_connect_quick_connect.ashlee_harris.quick_connect_id,
        data.aws_connect_quick_connect.abby_landers.quick_connect_id,
        data.aws_connect_quick_connect.kessia_guzman.quick_connect_id,
        data.aws_connect_quick_connect.kofi_bryant_harris.quick_connect_id,
        data.aws_connect_quick_connect.linda_goulet.quick_connect_id,
        data.aws_connect_quick_connect.mayra_gonzalez.quick_connect_id,
        data.aws_connect_quick_connect.shemika_redfearn.quick_connect_id,
        data.aws_connect_quick_connect.teddy_lowe.quick_connect_id,
        data.aws_connect_quick_connect.diana_hill.quick_connect_id,
        data.aws_connect_quick_connect.carlos_garcia_jurado.quick_connect_id,
        data.aws_connect_quick_connect.jairo_guerra_fandino.quick_connect_id,
        data.aws_connect_quick_connect.jeisson_lopez_agudelo.quick_connect_id,
        data.aws_connect_quick_connect.john_argote_castellanos.quick_connect_id,
        data.aws_connect_quick_connect.juan_macareno_restrepo.quick_connect_id,
        data.aws_connect_quick_connect.valeria_contreras_correa.quick_connect_id,
        data.aws_connect_quick_connect.april_liborio.quick_connect_id,
        data.aws_connect_quick_connect.constance_hands.quick_connect_id,
        data.aws_connect_quick_connect.damaris_amaya_torres.quick_connect_id,
        data.aws_connect_quick_connect.denys_jara_santos.quick_connect_id,
        data.aws_connect_quick_connect.detrius_smallwood.quick_connect_id,
        data.aws_connect_quick_connect.dilda_castillo_castro.quick_connect_id,
        data.aws_connect_quick_connect.frantia_lawton.quick_connect_id,
        data.aws_connect_quick_connect.shameil_porter.quick_connect_id,
        data.aws_connect_quick_connect.tracy_davenport.quick_connect_id,
        data.aws_connect_quick_connect.yury_beltran_vargas.quick_connect_id,
        data.aws_connect_quick_connect.andres_onoro_abdala.quick_connect_id,
        data.aws_connect_quick_connect.michelle_smith.quick_connect_id,
        data.aws_connect_quick_connect.trineaka_irby.quick_connect_id,
        # data.aws_connect_quick_connect.earline_mixon.quick_connect_id,
        data.aws_connect_quick_connect.athena_watkins.quick_connect_id,
        data.aws_connect_quick_connect.dallen_kimball.quick_connect_id,
        data.aws_connect_quick_connect.steve_assad.quick_connect_id,
        data.aws_connect_quick_connect.ihc_admin_coordinators_english.quick_connect_id,
        data.aws_connect_quick_connect.ihc_admin_coordinators_spanish.quick_connect_id,
        data.aws_connect_quick_connect.ihc_pcc_english.quick_connect_id,
        data.aws_connect_quick_connect.ihc_pcc_spanish.quick_connect_id,
        data.aws_connect_quick_connect.ihc_enrollment_welcome_team_spanish.quick_connect_id,
        data.aws_connect_quick_connect.ihc_enrollment_welcome_team_english.quick_connect_id,
        data.aws_connect_quick_connect.clinical_care_management_english.quick_connect_id,
        data.aws_connect_quick_connect.clinical_care_management_spanish.quick_connect_id,
        data.aws_connect_quick_connect.ga_ccv_scheduling_english.quick_connect_id,
        data.aws_connect_quick_connect.ga_ccv_scheduling_spanish.quick_connect_id,
        data.aws_connect_quick_connect.ccv_scheduling_english.quick_connect_id,
        data.aws_connect_quick_connect.ccv_scheduling_spanish.quick_connect_id,
        data.aws_connect_quick_connect.whv_scheduling_english.quick_connect_id,
        data.aws_connect_quick_connect.whv_scheduling_spanish.quick_connect_id,
        data.aws_connect_quick_connect.laquila_williams.quick_connect_id,
        data.aws_connect_quick_connect.esrd_english.quick_connect_id,
        data.aws_connect_quick_connect.esrd_spanish.quick_connect_id
      ]
      tags = local.tags
    }
  }

  queues = var.is_primary ? local.primary_queues : { for k in keys(local.primary_queues) : k => local.empty_queue }
}
