name: Create Amazon Connect Agent Statuses

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: "Environment"
        default: "dev"
      aws_region:
        type: string
        description: "Provide AWS region"
        default: "us-east-1"
      instance_id:
        type: string
        description: "The identifier of the Amazon Connect instance."
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  create-agent-states:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set AWS Account Number
      id: account-mapping
      run: |
        case "${{ inputs.environment }}" in
          dev)
            echo "aws_account=716537843042" >> $GITHUB_OUTPUT
            ;;
          uat)
            echo "aws_account=272103761966" >> $GITHUB_OUTPUT
            ;;
          prd)
            echo "aws_account=617842005266" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Unknown environment: ${{ inputs.environment }}"
            exit 1
            ;;
        esac

    - name: Install AWS CLI and jq
      run: |
        sudo apt-get update && sudo apt-get install -y awscli jq

    - name: Log in to AWS using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: arn:aws:iam::${{ steps.account-mapping.outputs.aws_account }}:role/ch-iam-shared-deployment-role-${{ inputs.environment }}

    - name: Create Amazon Connect Agent States
      run: |
        chmod +x ./scripts/add_agent_statuses.sh
        ./scripts/add_agent_statuses.sh "${{ inputs.instance_id }}" "${{ inputs.environment }}" "${{ steps.account-mapping.outputs.aws_account }}" "${{ inputs.aws_region }}"