name: Pull Request (Dev) workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  deployment-pipeline:
    name: Deploy to dev
    uses: CloverHealth/ccaas-shared-pipelines/.github/workflows/aws_infrastructure_deploy.yml@master
    with:
      WORKING_DIRECTORY: resources
      ENVIRONMENTS_CONFIG_DIR: environments
      AWS_REGION: us-east-1
      CI_ENVIRONMENT_NAME: dev
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}