name: Pull Request (Dev) workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g., dev, prod)'
        required: true
        default: 'dev'
      aws_region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  deployment-pipeline:
    name: Deploy to ${{ github.event.inputs.environment }}
    uses: Clover-Health-1/ccaas-shared-pipelines/.github/workflows/aws_infrastructure_deploy.yml@master
    with:
      WORKING_DIRECTORY: resources
      ENVIRONMENTS_CONFIG_DIR: environments
      AWS_REGION: ${{ github.event.inputs.aws_region }}
      CI_ENVIRONMENT_NAME: ${{ github.event.inputs.environment }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}