name: Deploy to UAT Environment

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write
  issues: write 
  pull-requests: write

jobs:
  deployment-pipeline:
    name: Deploy to uat
    uses: CloverHealth/ccaas-shared-pipelines/.github/workflows/aws_infrastructure_deploy.yml@master
    with:
      WORKING_DIRECTORY: resources
      ENVIRONMENTS_CONFIG_DIR: environments
      AWS_REGION: us-east-1
      CI_ENVIRONMENT_NAME: uat
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  create-release-tag:
    name: Create Release Tag for Production
    needs: deployment-pipeline
    uses: CloverHealth/ccaas-shared-pipelines/.github/workflows/create-release-tag.yml@master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    with:
      TAG_PREFIX: release-v
      REPOSITORY: ${{ github.repository }}
      ENVIRONMENT: uat
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}      